window.pppQuestions = {
	"en": [
		"What is the birth date of George Washington?",
		"Who is the president of France?",
		"What is the capital of Australia?",
		"What is the birth date of the president of the United States?",
		"Who is the author of Foundation?",
		"Who is the director of \"Pulp Fiction\"?",
		"Who is the director of \"A Clockwork Orange\"?",
		"Sherlock Holmes",
		"Guatemala",
		"Who is Bach?",
		"What is “P=NP”?",
		"Who is the author of “Le Petit Prince”?",
		"What is the capital of India?",
		"Who is the prime minister of France?",
		"What is the birth date of the president of the United States?",
		"Who are the Beatles' members?",
		"sqrt(180)",
		"N[Pi, 42]",
		"Limit[Sum[1/i, {i,1,n}]-Log[n], n->Infinity]",
		"Sum[x^n/n!, {n,0,Infinity}]",
		"Solve[Exp[x]/2+Exp[-x]/2==y,x]",
		"dsolve(f'(x) + f(x) = 0, f(x))",
		"Who are the daughters of the wife of the husband of the wife of the president of the United States?",
		"Where was Ulysses S. Grant born?",
		"Where was George Washington born?",
		"Where is the Taj Mahal?",
		"Who is the President of Ghana?",
		"What is Head Start?",
		"Who wrote \"Dubliners\"?",
		"Who wrote \"Hamlet\"?",
		"What is the population of Japan?",
		"What is the population of France?",
		"What is a caldera?",
		"What is the nationality of Jackson Pollock?",
		"What is the zip code for Lyon?",
		"What is the atomic number of oxygen?",
		"What is the atomic number of polonium?",
		"What is Boston Strangler's name?",
		"When was D-Day?",
		"What is an annotated bibliography?",
		"Who is the mayor of Paris?",
		"Who is the mayor of London?",
		"Where is the Sagrada Familia?",
		"Where is \"Notre-Dame de Paris\"?",
		"Where is the Everest?",
		"Where is the parliament of China?",
		"Where is the Panama canal?",
		"What is the location of the Alps?",
		"What is the location of the Great Barrier Reef?",
		"What are the official names of the European Union?",
		"What are the official languages of the European Union?",
		"What is the flag of the European Union?",
		"What are the capitals of the European Union?",
		"Where are the capitals of the European Union?",
		"What are the borders of Mexico?",
		"What is the time zone of France?",
		"What is the time zone of San Francisco?",
		"Where is the Bay Area?",
		"What is the music genre of the Beatles?",
		"What is the music genre of Bob Marley?",
		"What is the film genre of Full Metal Jacket?"
	],
	"fr": [
		"Quelle est la date de naissance de George Washington?",
		"Qui est le président de la France ?",
		"Quelle est la capitale de l'Australie ?",
		"Qui est l'auteur de Fondation ?",
		"Qui est le PDG de Google ?",
		"Sherlock Holmes",
		"Guatemala",
		"Qui est Bach?",
		"Qu'est-ce que “P=NP”?",
		"Qui est l'auteur du Petit Prince ?",
		"Quel est la capitale de l'Inde ?",
		"Qui est le premier ministre de la France ?",
		"sqrt(180)",
		"N[Pi, 42]",
		"Limit[Sum[1/i, {i,1,n}]-Log[n], n->Infinity]",
		"Sum[x^n/n!, {n,0,Infinity}]",
		"Solve[Exp[x]/2+Exp[-x]/2==y,x]",
		"dsolve(f'(x) + f(x) = 0, f(x))",
		"Où est le musée de Louvre ?",
		"Qui est le président du Ghana ?",
		"Quelle est la population de la France ?",
		"Quelle est la population du Japon ?",
		"Qu'est-ce qu'une  caldera ?",
		"Quelle est la nationalité de Jackson Pollock ?",
		"Quel est le code postal de Lyon ?",
		"Quel est le numéro atomique de l'oxygène ?",
		"Quel est le numéro atomique du Polonium ?",
		"Quand était la prise de la Bastille ?",
		"Qu'est-ce qu'une bibliographie ?",
		"Qui est le maire de Paris ?",
		"Qui est le maire de Londre ?",
		"Où est la Sagrada Familia ?",
		"Où est Notre-Dame de Paris ?",
		"Où est l'Everest ?",
		"Où est le sénat français ?",
		"Où est le canal de Panama ?",
		"Quelle est la localisation des Alpes ?",
		"Quelle est la localisation de la Grande barrière de corail ?",
		"Quels sont les noms officiels de l'Union Européenne ?",
		"Quels sont les langues officielles de l'UE ?",
		"Quel est le drapeau de l'Union Européenne ?",
		"Quels sont les capitales de l'Union Européenne ?",
		"Où sont les capitales de l'Union Européenne ?",
		"Quels sont les frontières de Mexico ?",
		"Quel est le fuseau horaire de la France ?",
		"Où est le bassin d'Arcachon ?"
	]
};
