window.pppQuestions = [
	"What is the birth date of George Washington?",
	"Who is the president of France?",
	"What is the capital of Australia?",
	"What is the birth date of the president of the United States?",
	"Who is the author of Foundation?",
	"Who is the director of \"Pulp Fiction\"?",
	"Sherlock Holmes",
	"Guatemala",
	"Who is Bach?",
	"What is “P=NP”?",
	"Who is the author of “Le Petit Prince”?",
	"What is the capital of India?",
	"Who is the prime minister of France?",
	"What is the birth date of the president of the United States?",
	"Who are the Beatles' members?",
	"sqrt(180)",
	"N[Pi, 42]",
	"Limit[Sum[1/i, {i,1,n}]-Log[n], n->Infinity]",
	"Integrate[Sin[x*y], {x, 0, 1}, {y, 0, x}]",
	"Sum[x^n/n!, {n,0,Infinity}]",
	"Solve[Exp[x]/2+Exp[-x]/2==y,x]",
	"What is the cappyttal of Franse?",
	"Who are the daughters of the wife of the husband of the wife of the president of the United States?",
	"Where was Ulysses S. Grant born?",
	"Where was George Washington born?",
	"Where is the Taj Mahal?",
	"Who is the President of Ghana?",
	"What is Head Start?",
	"Who wrote \"Dubliners\"?",
	"Who wrote \"Hamlet\"?",
	"What is the population of Japan?",
	"What is the population of France?",
	"What is a caldera?",
	"What is the nationality of Jackson Pollock?",
	"What is the zip code for Lyon?",
	"What is the world's population?",
	"What is the atomic number of oxygen?",
	"What is the atomic number of polonium?",
	"What is the Boston Strangler's name?",
	"When was D-Day?",
	"What is an annotated bibliography?",
	"Who is the mayor of Paris?",
	"Who is the mayor of London?"
];
