window.pppQuestions = {
	"en": [
		"What is the birth date of George Washington?",
		"Who is the president of France?",
		"What is the capital of Australia?",
		"What is the birth date of the president of the United States?",
		"Who is the author of Foundation?",
		"Who is the director of \"Pulp Fiction\"?",
		"Who is the director of \"A Clockwork Orange\"?",
		"Sherlock Holmes",
		"Guatemala",
		"Who is Bach?",
		"What is “P=NP”?",
		"Who is the author of “Le Petit Prince”?",
		"What is the capital of India?",
		"Who is the prime minister of France?",
		"What is the birth date of the president of the United States?",
		"Who are the Beatles' members?",
		"sqrt(180)",
		"N[Pi, 42]",
		"Limit[Sum[1/i, {i,1,n}]-Log[n], n->Infinity]",
		"Sum[x^n/n!, {n,0,Infinity}]",
		"Solve[Exp[x]/2+Exp[-x]/2==y,x]",
		"dsolve(f'(x) + f(x) = 0, f(x))",
		"Who are the daughters of the wife of the husband of the wife of the president of the United States?",
		"Where was Ulysses S. Grant born?",
		"Where was George Washington born?",
		"Where is the Taj Mahal?",
		"Who is the President of Ghana?",
		"What is Head Start?",
		"Who wrote \"Dubliners\"?",
		"Who wrote \"Hamlet\"?",
		"What is the population of Japan?",
		"What is the population of France?",
		"What is a caldera?",
		"What is the nationality of Jackson Pollock?",
		"What is the zip code for Lyon?",
		"What is the atomic number of oxygen?",
		"What is the atomic number of polonium?",
		"What is Boston Strangler's name?",
		"When was D-Day?",
		"What is an annotated bibliography?",
		"Who is the mayor of Paris?",
		"Who is the mayor of London?",
		"Where is the Sagrada Familia?",
		"Where is \"Notre-Dame de Paris\"?",
		"Where is the Everest?",
		"Where is the parliament of China?",
		"Where is the Panama canal?",
		"What is the location of the Alps?",
		"What is the location of the Great Barrier Reef?",
		"What are the official names of the European Union?",
		"What are the official languages of the European Union?",
		"What is the flag of the European Union?",
		"What are the capitals of the European Union?",
		"Where are the capitals of the European Union?",
		"What are the borders of Mexico?",
		"What is the time zone of France?",
		"What is the time zone of San Francisco?",
		"Where is the Bay Area?",
		"What is the music genre of the Beatles?",
		"What is the music genre of Bob Marley?",
		"What is the film genre of Full Metal Jacket?"
	],
	"fr": []
};
